name: .NET Core Build and Run Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies for project
      run: dotnet restore ~/work/NmeaParser/NmeaParser/NmeaParser/
    - name: Build
      run: dotnet build ~/work/NmeaParser/NmeaParser/NmeaParser/NmeaParser.csproj --configuration Release --no-restore
    - name: Install dependencies for test project
      run: dotnet restore ~/work/NmeaParser/NmeaParser/NmeaParser.Test/
    - name: Test
      run: dotnet test ~/work/NmeaParser/NmeaParser/NmeaParser.Test/NmeaParser.Test.csproj --no-restore --verbosity normal
